# Generated by Django 4.2.18 on 2025-02-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_generatednotes_delete_generatedpdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatednotes',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
